version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

x-restart: &restart-unless-stopped
  restart: unless-stopped

services:
  beacon:
    container_name: beacon-chain
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:${PRYSM_DOCKER_TAG}
    restart: always
    hostname: beacon-chain
    command:
      - "--config-file=/config/beacon.yaml"
      - "--http-web3provider=${HTTP_WEB3PROVIDER}"
    ports:
      - "13000:13000"
      - "12000:12000/udp"
    dns:
      - 1.1.1.1
    volumes:
      - ./config/beacon.yaml:/config/beacon.yaml:ro
      - ./beacon:/data
    <<: *logging
  validator:
    container_name: validator
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_DOCKER_TAG}
    <<: *restart-unless-stopped
    restart: on-failure
    hostname: validator
    depends_on:
      - beacon
    command: --config-file=/config/validator.yaml
    volumes:
      - ./config/validator.yaml:/config/validator.yaml:ro
      - ./validator:/data
    <<: *logging

  slasher:
    container_name: slasher
    image: gcr.io/prysmaticlabs/prysm/slasher:${PRYSM_DOCKER_TAG}
    <<: *restart-unless-stopped
    hostname: slasher
    depends_on:
      - beacon
    command: --config-file=/config/slasher.yaml
    volumes:
      - ./config/slasher.yaml:/config/slasher.yaml:ro
      - ./slasher:/data
    <<: *logging

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    <<: *restart-unless-stopped
    hostname: prometheus
    user: root
    command:
      - "--storage.tsdb.retention.time=31d"
      - "--storage.tsdb.path=/data"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/data
    <<: *logging

  grafana:
    container_name: grafana
    image: grafana/grafana:7.0.0
    <<: *restart-unless-stopped
    hostname: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    <<: *logging
