# Check files
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker Compose Lint
        run: docker-compose config --quiet

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./infra/terraform
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra/terraform
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./infra/terraform
